<?php

/**
 * Implements hook_library_info().
 */
function codemirror_widget_library_info() {
  $libraries['codemirror'] = array(
    'title' => 'CodeMirror',
    'website' => 'http://codemirror.net/',
    'version' => '4.11',
    'js' => array(
      'libraries/codemirror/codemirror.js',
    ),
    'css' => array(
      'libraries/codemirror/codemirror.css',
    ),
  );
  return $libraries;
}


/**
 * Implements hook_field_widget_info().
 */
function codemirror_widget_field_widget_info() {
  return array(
    'text_codemirror' => array(
      'label' => t('CodeMirror'),
      'description' => t('Text area edit widget using the CodeMirror library'),
      'field types' => array('text_long'),
      'settings' => array(
        'mode' => 'css',
        'theme' => 'default',
        'autoresize' => TRUE,
        'rows' => 9,
        'plugins' => array(),
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function codemirror_widget_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  if ($widget['type'] == 'text_codemirror') {
    $form['mode'] = array(
      '#type' => 'select',
      '#title' => t('Language mode'),
      '#default_value' => $settings['mode'],
      '#required' => TRUE,
      '#options' => _codemirror_get_available_modes(),
    );
    $form['theme'] = array(
      '#type' => 'select',
      '#title' => t('Theme'),
      '#default_value' => $settings['theme'],
      '#required' => TRUE,
      '#options' => _codemirror_get_available_themes(),
    );
    $form['rows'] = array(
      '#type' => 'textfield',
      '#title' => t('Rows'),
      '#default_value' => $settings['rows'],
      '#required' => TRUE,
    );
    $form['autoresize'] = array(
      '#type' => 'checkbox',
      '#title' => t('Autoresize'),
      '#default_value' => $settings['autoresize'],
    );
  }
  return $form;
}

/**
 * Implements hook_field_widget_form().
 */
function codemirror_widget_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $id = array(
    'edit',
    str_replace('_', '-', $element['#field_name']),
    $langcode,
    $delta,
    'value',
  );
  $id = implode('-', $id);
  $settings = array(
    $delta => $instance['widget']['settings'],
  );

  $library_path = 'libraries/codemirror';
  $main_widget = $element + array(
    '#type' => 'textarea',
    '#default_value' => isset($items[$delta]['value']) ? $items[$delta]['value'] : '',
    '#rows' => $instance['widget']['settings']['rows'],
    '#attached' => array(
      'js' => array(
        array(
          'data' => backdrop_get_path('module', 'codemirror_widget') . '/codemirror_widget.js',
          'type' => 'file',
        ),
        array(
          'data' => $library_path . '/lib/codemirror.js',
          'weight' => -10,
          'type' => 'file',
        ),
      ),
      'css' => array(
        array(
          'data' => $library_path . '/lib/codemirror.css',
          'type' => 'file',
        ),
      ),
    ),
  );
  $main_widget['#attributes']['class'][] = 'codemirror';
  $element['#attached']['js'][] = array(
    'data' => array('codemirror' => $settings),
    'type' => 'setting',
  );
  if ($instance['widget']['settings']['autoresize']) {
    $main_widget['#attached']['css'][] = array(
      'data' => '.CodeMirror .CodeMirror-scroll { height: auto; }',
      'type' => 'inline',
    );
  }
  $theme = $instance['widget']['settings']['theme'];
  if ($theme != 'default') {
    $main_widget['#attached']['css'][] = array(
      'data' => $library_path . "/theme/{$theme}.css",
      'type' => 'file',
    );
  }
  $mode = $instance['widget']['settings']['mode'];
  $main_widget['#attached']['js'][] = array(
    'data' => $library_path . "/mode/{$mode}/{$mode}.js",
    'type' => 'file',
    'weight' => '10',
  );
  //debug($element);
  $element['value'] = $main_widget;
  return $element;
}

function _codemirror_get_available_modes() {
  $library_path = 'libraries/codemirror/mode';
  $modes = file_scan_directory($library_path, '/.*/', array(
    'recurse' => FALSE,
    'key' => 'name',
    )
  );
  foreach ($modes as $name => $file) {
    $modes[$name] = $name;
  }
  return $modes;
}

function _codemirror_get_available_themes() {
  $library_path = 'libraries/codemirror/theme';
  $themes = file_scan_directory($library_path, '/\.css/', array(
    'key' => 'name',
    )
  );
  foreach ($themes as $name => $theme) {
    $themes[$name] = $name;
  }
  return array('default' => 'default') + $themes;
}






